### ISSUE TITLE
Working fine on android 5 but not reading sms on versions higher.

### ISSUE THREAD

**Issue by Hook-Da** [KetanDhopeshwarkar/react-native-read-sms#5]
I installed package and tested it on my old device with android version 5.1.1 and it worked fine but when I installed the same with this package on devices with android 8 and 10 it didn't work.

Edit: When debbuging on android higher versions and outputting in console it's working but when stop outputting in console it stop working. Could not understand what the reason of it.

**Comment by 3zvan** [comment]
You might need to use the `PermissionsAndroid` API to ask for permission from the user. Since API 23 (Android 6.0) you have to manually ask for "dangerous" permissions since they are not displayed before installation. See details [here](https://developer.android.com/guide/topics/permissions/overview).

**Comment by SohaibKtb** [comment]
+1

**Comment by ketan1062** [comment]
I have tested it on android 8 and 10 and its works fine.
Please make sure startReadSMS will be called after ReadSms.requestReadSMSPermission.
